### ISSUE TITLE
Version Docker Images

### ISSUE THREAD

**Issue by jpoon** [sekka1/kubernetes-fluentd-loggly#3]
We came across this [blog post](https://www.loggly.com/blog/send-kubernetes-logs-loggly/#) of yours and it's exactly what we want to do. Can you version the Docker image (https://hub.docker.com/r/garland/kubernetes-fluentd-loggly)?

When deploying this daemonset into our Kubernetes cluster, we'd like to pin the Docker image to a particular version.

cc @cardboardboxb

**Comment by sekka1** [comment]
Can do.  Let me do that in the next few days.  Thanks for using it.  Let me know if you see any issues.

**Comment by sekka1** [comment]
I added version 1.0 and changed the daemonset files to use that.  Thanks for the suggestion:  

https://github.com/sekka1/kubernetes-fluentd-loggly/pull/4

**Comment by jpoon** [comment]
Thanks! We actually created a helm chart to deploy Loggly leveraging your work: https://github.com/jpoon/chart-loggly

Do you work for loggly? There were a couple of improvements that could be made to the container. Particularly, if the container warned if the API-key were invalid.

**Comment by sekka1** [comment]
Nice!  I dont work for Loggly.  Im an independent consultant that just happens to use Loggly and Kubernetes.   

You probably can change this to `1.0`:  https://github.com/jpoon/loggly/blob/master/values.yaml#L6

To warn if the API key is invalid...would it have to do a preflight check before it starts?  Or is there an easier way to tell?

**Comment by jpoon** [comment]
> You probably can change this to 1.0: https://github.com/jpoon/loggly/blob/master/values.yaml#L6

Thanks. Updated the chart.

> To warn if the API key is invalid...would it have to do a preflight check before it starts? Or is there an easier way to tell?

At the moment, regardless of whether the API key is valid or not, there is no logging message. What I'm hoping for is if the API key is incorrect, the container should log something (401 unauth, etc).
